{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/caduAa/MPLC-/blob/main/MPLC_mys.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "from scipy.fft import fft2, ifft2\n",
        "import matplotlib.pyplot as plt\n",
        "%matplotlib inline"
      ],
      "metadata": {
        "id": "Y6CF7HBPB4L5"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "ra2BzAYY7j3T",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "1f92092d-f815-41dd-9143-e77d157cc1d3"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.10/dist-packages/numpy/fft/helper.py:162: RuntimeWarning: divide by zero encountered in divide\n",
            "  val = 1.0 / (n * d)\n",
            "/usr/local/lib/python3.10/dist-packages/numpy/fft/helper.py:169: RuntimeWarning: invalid value encountered in multiply\n",
            "  return results * val\n",
            "<ipython-input-2-888de37d84ab>:159: RuntimeWarning: invalid value encountered in sqrt\n",
            "  H = np.exp(-1j *dz * np.sqrt((k)**2-(K_x)**2-(K_y)**2));\n",
            "<ipython-input-2-888de37d84ab>:90: ComplexWarning: Casting complex values to real discards the imaginary part\n",
            "  Vol_U1[k] = split_step(Vol_U1[k - 1] * t1, H);\n",
            "<ipython-input-2-888de37d84ab>:114: ComplexWarning: Casting complex values to real discards the imaginary part\n",
            "  Vol_U1[k] = split_step(Vol_U1[k - 1] * t1, H);\n"
          ]
        }
      ],
      "source": [
        "# For the field propagation\n",
        "def split_step(U, H):\n",
        "  U_fft = np.fft.fft2(U);                                                       #Field's Fourier Transform\n",
        "  U_propfft = U_fft * H;                                                        # Propagation in Fourier Space\n",
        "  return np.fft.ifft2(U_propfft);                                               # Back to Real Space\n",
        "\n",
        "## For initial fields\n",
        "def gaussian_beam(w0, region):\n",
        "  j_k = 1j * k;\n",
        "  z0 = 0.5* k * ((w0)**2);                                                      #Rayleigh range\n",
        "  W = w0 * np.sqrt(1 + (zList / z0) **2);                                       #Beam waist\n",
        "  i = 0;\n",
        "  X,Y = region;\n",
        "  RHO = np.sqrt(X**2+Y**2);\n",
        "\n",
        "  R = np.zeros(b);\n",
        "  for z in zList:\n",
        "    if z == 0:\n",
        "      pass\n",
        "    else:\n",
        "      R[i] = z * (1 + (z0 / z) **2);\n",
        "      i = i + 1;\n",
        "\n",
        "  j_zeta = -1j * z0;\n",
        "  A0 = 1.;\n",
        "  A = (w0 / W);\n",
        "  WW = W ** 2.;\n",
        "\n",
        "  U = A0 * np.exp(-RHO**2 / W[0] ** 2);\n",
        "\n",
        "  return U;\n",
        "\n",
        "def laguerre_gauss_beam(w0, region, l, m):\n",
        "\n",
        "  j_k = 1j * k;\n",
        "  z0 = 0.5* k * ((w0)**2);                                                      #Rayleigh range\n",
        "  W = w0 * np.sqrt(1 + (zList / z0) **2);                                       #Beam waist\n",
        "  i = 0;\n",
        "  X,Y = region;\n",
        "  RHO = np.sqrt(X**2+Y**2);\n",
        "  PHI = np.arctan(Y/X);\n",
        "\n",
        "  R = np.zeros(b);\n",
        "  for z in zList:\n",
        "    if z == 0:\n",
        "      pass\n",
        "    else:\n",
        "      R[i] = z * (1 + (z0 / z) **2);\n",
        "      i = i + 1;\n",
        "\n",
        "  j_zeta = -1j * z0;\n",
        "  Oz = np.arctan(zList/z0);\n",
        "  A0 = 1.;\n",
        "  A = (w0 / W);\n",
        "  WW = W ** 2.;\n",
        "\n",
        "  U = A0 * ((RHO / W[0]) ** l) * np.exp(-RHO ** 2 / W[0] ** 2) * np.exp(- (j_k * zList[0]) - 1j * l * PHI + 1j * (l + 2*m + 1) * Oz[0]);                   #terminar\n",
        "\n",
        "  return U;\n",
        "\n",
        "#Optimizing...\n",
        "def optimizing_phases(U1, U2, region, num_iterations, numsteps):\n",
        "\n",
        "  numsteps = 250;\n",
        "  tolerance = 1.e-3;\n",
        "  phases = np.array([np.zeros_like(U1) for step in range(numsteps)]);\n",
        "  phases_grad = np.array([np.zeros_like(U1) for step in range(numsteps)]);\n",
        "  phases_masks = phases.shape[0]\n",
        "  t1 = np.array([np.zeros_like(U1) for step in range(numsteps)]);\n",
        "  t2 = np.array([np.zeros_like(U1) for step in range(numsteps)]);\n",
        "  a = np.array([np.zeros_like(U1) for step in range(numsteps)]);\n",
        "\n",
        "  Vol_U1 = np.array([np.ones_like(U1) for step in range(numsteps)]);\n",
        "  Vol_U1 = Vol_U1 * U1;\n",
        "  Vol_U2 = np.array([np.ones_like(U2) for step in range(numsteps)]);\n",
        "  Vol_U2 = Vol_U2 * U2;\n",
        "\n",
        "  u1 = Vol_U1;\n",
        "  u2 = Vol_U2;\n",
        "\n",
        "  k = 0;\n",
        "  i = 0;\n",
        "\n",
        "  for k in range(1, numsteps):\n",
        "\n",
        "    t1 = np.exp(1j * phases[k - 1]);\n",
        "    t2 = np.exp(1j * phases[-(k + 1)]);\n",
        "    Vol_U1[k] = split_step(Vol_U1[k - 1] * t1, H);\n",
        "    Vol_U2[-(k + 1)] = split_step(Vol_U2[-k] * t2, np.conj(H));\n",
        "\n",
        "  E0 = np.real(np.mean(np.abs(Vol_U1-Vol_U2)**2));\n",
        "\n",
        "  if (E0 <= tolerance):\n",
        "    return phases, E0;\n",
        "  else:\n",
        "    for i in range(num_iterations):\n",
        "\n",
        "      phases_grad = np.angle(np.conj(Vol_U1) * Vol_U2);\n",
        "      a = phases_grad;\n",
        "      k = 0;\n",
        "      Vol_U1 = u1;\n",
        "      Vol_U2 = u2;\n",
        "\n",
        "      for k in range(1, numsteps):\n",
        "\n",
        "        t1 = np.exp(1j * phases_grad[k - 1]);\n",
        "        t2 = np.exp(1j * phases_grad[-(k + 1)]);\n",
        "        Vol_U1[k] = split_step(Vol_U1[k - 1] * t1, H);\n",
        "        Vol_U2[-(k + 1)] = split_step(Vol_U2[-k] * t2, np.conj(H));\n",
        "        phases_grad = np.angle(np.conj(Vol_U1) * Vol_U2);\n",
        "\n",
        "      E = np.real(np.mean(np.abs(Vol_U1 - Vol_U2) ** 2));\n",
        "\n",
        "      if (E < E0):\n",
        "        #phases = phases_grad;\n",
        "        E0 = E;\n",
        "        if (E0 <= tolerance):\n",
        "          phases = a;\n",
        "          return phases, E0;\n",
        "        else:\n",
        "            break\n",
        "\n",
        "  return phases, E0;\n",
        "\n",
        "\n",
        "##Parameters\n",
        "l=np.linspace(-10,+10,50);\n",
        "X, Y = np.meshgrid(l,l);\n",
        "N = 350;\n",
        "L = 80;\n",
        "n0 = 1.5078;\n",
        "lambda_ = 640e-3;\n",
        "k0 = 2*np.pi/lambda_;\n",
        "k = k0*n0;\n",
        "\n",
        "RHO = np.sqrt(X**2+Y**2);\n",
        "\n",
        "dx, dy = X[1] - X[0], Y[1] - Y[0];\n",
        "dz = 20;\n",
        "zFinal = 5000;\n",
        "Nz = np.round(zFinal/dz);\n",
        "Nzint = int(Nz);\n",
        "zList = np.linspace(0,zFinal, Nzint);\n",
        "b = zList.size;                                                                 #Number of layers (and steps)\n",
        "pmlWidth = L/8;\n",
        "insideIndex = np.round(N*[pmlWidth/L, 1-pmlWidth/L]);\n",
        "region = (insideIndex[0],insideIndex[1]);\n",
        "\n",
        "\n",
        "#For Fourier Transform\n",
        "k_x, k_y = 2. * np.pi * np.fft.fftfreq(50, dx), 2. * np.pi * np.fft.fftfreq(50, dy);\n",
        "K_x, K_y = np.meshgrid(k_x, k_y);\n",
        "H = np.exp(-1j *dz * np.sqrt((k)**2-(K_x)**2-(K_y)**2));\n",
        "\n",
        "\n",
        "##Initial Beam conditions...\n",
        "w0 = 10.;                               #Beam Waist\n",
        "beamDist = 0.0;\n",
        "U1 = gaussian_beam(w0, region = (X,Y));\n",
        "U2 = laguerre_gauss_beam(w0, region = (X,Y), l = 1, m = 0);\n",
        "\n",
        "phases, E_sqr = optimizing_phases(U1, U2, region = (X,Y), num_iterations = 10, numsteps = 250);\n",
        "\n",
        "#plt.imshow(np.abs(U1) ** 2., extent=[l[0],l[-1],l[0],l[-1]]);\n",
        "\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [],
      "metadata": {
        "id": "IbedEqJD6TJ_"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from matplotlib import pyplot as plt\n",
        "import matplotlib.animation as animation\n",
        "\n",
        "plt.rcParams[\"animation.html\"] = \"jshtml\"\n",
        "plt.rcParams['figure.dpi'] = 150\n",
        "plt.ioff()\n",
        "\n",
        "fig, ax = plt.subplots();\n",
        "graph = ax.imshow(phases[0])\n",
        "\n",
        "def integrate(i):\n",
        "  graph.set_data(phases[i]);\n",
        "\n",
        "animation.FuncAnimation(fig, integrate, frames= phases_masks, interval=(2000./phases_masks))"
      ],
      "metadata": {
        "id": "rFy_SeUtFSS7"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}